### ISSUE TITLE
Crashed on GraphicsCapture!winrt::throw_hresult

### ISSUE THREAD

**Issue by PanSnow** [Microsoft/Windows.UI.Composition-Win32-Samples#139] opened 2024-11-06 09:31 UTC
Based on the code implementation logic in the previous post(https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/138), I also encountered a crash issue on GraphicsCapture!winrt::throw_hresult. Can anyone give me some optimization suggestions to resolve this?
The following is the relevant crash dump and call stack.  may be it can locate the problem faster
[sdkdump-2024-11-05-15-08-09.dmp](https://github.com/user-attachments/files/17644704/sdkdump-2024-11-05-15-08-09.dmp)
![Image](https://github.com/user-attachments/assets/cb27af69-9306-4eeb-af9f-d80cd2495b36)

[sdkdump-2024-10-29-15-41-51.dmp](https://github.com/user-attachments/files/17644705/sdkdump-2024-10-29-15-41-51.dmp)
![Image](https://github.com/user-attachments/assets/f431a40a-e454-4bbd-b027-dc053e194103)

[sdkdump-2024-11-05-07-47-08.dmp](https://github.com/user-attachments/files/17644703/sdkdump-2024-11-05-07-47-08.dmp)
![Image](https://github.com/user-attachments/assets/75497341-0ffe-4349-89f7-b8431698d203)

**Comment by robmikh** [comment] 2024-11-06 10:50
Generally, crashes will be reported to us through diagnostic systems.

These seem unrelated to your previous issue. Unfortunately, the first and third dumps don't seem to have any actionable information. Your second dump seems to be caused by a device lost event, as the error code is DXGI_ERROR_DEVICE_REMOVED. It appears there's a bug internally that if this happens at an inopportune time, we don't properly bubble up the error. Thanks for bringing it to our attention, I've filed a bug internally.

In general, when you receive DXGI_ERROR_DEVICE_REMOVED, you'll need to create a new D3D11 device and recreate all of your D3D11 resources. After that you will need to call Recreate on your frame pool with the new device.

I'm going to close this issue for now. Feel free to ask questions.

**Closed as completed by robmikh** 2024-11-06 10:50 UTC

**Comment by PanSnow** [comment] 2024-11-07 13:21
Thanks for your reply, usually I can't know when the device is lost, so there is no suitable time to recreate a new device. I see the top stack is RaiseException, can I catch this error using structured exception handling(__try...__excpet().. ) to avoid this crash?

> Generally, crashes will be reported to us through diagnostic systems.
> 
> These seem unrelated to your previous issue. Unfortunately, the first and third dumps don't seem to have any actionable information. Your second dump seems to be caused by a device lost event, as the error code is DXGI_ERROR_DEVICE_REMOVED. It appears there's a bug internally that if this happens at an inopportune time, we don't properly bubble up the error. Thanks for bringing it to our attention, I've filed a bug internally.
> 
> In general, when you receive DXGI_ERROR_DEVICE_REMOVED, you'll need to create a new D3D11 device and recreate all of your D3D11 resources. After that you will need to call Recreate on your frame pool with the new device.
> 
> I'm going to close this issue for now. Feel free to ask questions.

**Comment by robmikh** [comment] 2024-11-07 23:10
Unfortunately, no. We'll need to make a change on our side.
