### ISSUE TITLE
CreateForWindow 0x80070057

### ISSUE THREAD

**Issue by zhaokaixs** [Microsoft/Windows.UI.Composition-Win32-Samples#133] opened 2024-06-19 08:07 UTC
ScreenCaptureforHWND.exe is running on new desktop (CreateDesktop and SwitchDesktop),CreateForWindow return 0x80070057
CreateForMonitor work well

![image](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/assets/7833585/f594a8f6-0525-44f6-9120-a601c2071f75)

**Comment by robmikh** [comment] 2024-06-19 19:57
What window are you trying to capture?

The issue is that not all windows are supported by Windows.Graphics.Capture at this time. The general rule of thumb is that if you can see it in the Alt+Tab interface, you can capture it. Child windows are not supported.

**Comment by zhaokaixs** [comment] 2024-06-20 03:25
I just tested a method that terminated  explorer..exe process, and CreatForMonitor will return (0x800706be)，
My usage scenario is to have a clean desktop

**Comment by robmikh** [comment] 2024-06-20 03:29
Sorry, the explorer process must be running. Explorer facilitates the initial linkage of the capture pipeline.

**Comment by robmikh** [comment] 2024-06-20 03:31
I'm going to close this issue since capturing without explorer is not supported with Windows.Graphics.Capture.

**Closed as not planned** 2024-06-20 03:31 UTC

**Comment by zhaokaixs** [comment] 2024-06-20 05:22
> 我将关闭此问题，因为 Windows.Graphics.Capture 不支持不使用资源管理器进行捕获。

Thank you for your reminder. Then I will think of other ways to hide desktop icons, right-click menus, and taskbars.

**Comment by zhaokaixs** [comment] 2024-06-24 07:59
> 抱歉，explorer 进程必须正在运行。explorer 有助于捕获管道的初始链接。

I tested the new solution, CreateDesktop(L"new_hdesk"), and CreateProces explorer.exe on new_hdesk, CreateForWindow still returns 0x80070057

**Comment by theonewolf** [comment] 2024-10-31 16:24
@robmikh I see a lot of limitations scattered throughout GitHub.  Are the limitations all documented in one place?

1. Explorer must be running,
2. Windows visible to Task switcher (alt+tab)
3. Non-child windows

Anything else?

It's confusing to randomly hit these / not understand why things aren't working without the limitations documented in one place.

What is a suggested typical fallback?  Use PrintWindow?

**Comment by robmikh** [comment] 2024-10-31 19:21
Nope that's about it. 

As for a fallback, sure PrintWindow is an option.

**Comment by theonewolf** [comment] 2024-11-01 11:35
@robmikh thank you for timely responses.

**Comment by theonewolf** [comment] 2024-11-21 16:01
@robmikh we have limitations noted down on this ticket, and one alternative method.

I see three alternatives, are there any others you'd add to this list?  More alternatives require a kernel driver?

1. PrintWindow
2. BitBlt (doesn't work for hardware accelerated UIs though)
3. DXGI desktop duplication

This ticket can serve as documentation on limitations of WGC, as well as all the alternatives!

**Comment by robmikh** [comment] 2024-11-21 20:49
I think the only other one I'd add is the indirect display driver. That's one I'd look at if I was building an application/solution that looked like RDP.

**Comment by theonewolf** [comment] 2024-11-21 23:42
Thanks once again @robmikh.  I’m actually exploring the best way to take screenshots of any application.  I don’t think there’s one single “best” way.  Every approach seems to have some cons.  I’ll probably implement multiple.
