### ISSUE TITLE
Crash in CreateForWindow in some cases

### ISSUE THREAD

**Issue by visuall** [microsoft/Windows.UI.Composition-Win32-Samples#48] opened 2020-02-25 12:00 UTC
Hello,

I have noticed that CreateForWindow  crashes in case the HWND provided does not have a border. Is this normal ?

Best Regards,
Nick

**Comment by robmikh** [comment] 2020-02-25 18:20
I'm unable to comment on your specific case without more information (is the window top-level? what other stylings are you using? etc) but not all window handles are guaranteed to produce capture items. This is partially why we have the filtering mechanism in the sample.

**Comment by visuall** [comment] 2020-02-27 10:09
The question is not how the fix the app. In one or other way this can be done I guess ... try/catch, check results, etc. Question is why the Windows API will not behave properly and clearly crash with some windows. May be some additional calls or other changes in the way it is used has to be made?

For example this works with a standard window with styles: WS_VISIBLE, WS_CLIPSIBLINGS, WS_CLIPCHILDREN,  WS_OVERLAPPED, WS_MINIMIZEBOX, WS_MAXIMIZEBOX but if we remove the caption bar which leads to removal of WS_CAPTION, WS_SYSMENU, WS_THICKFRAME the above API crashes with access violation and if this can be avoided somehow so that the API behaves properly.

**Comment by jeffstall** [comment] 2020-02-27 17:09
Do you have a very simple Visual Studio project that can reproduce the problem?

**Comment by nop144d** [comment] 2022-03-22 15:24
I'm having the same issue in this simplified scenario:

I create a DLL with `Init()` function. In this function, I create a thread and wait on a condition variable which is signaled when the initialization is complete (including creating a _capture item_). In this thread, I create another thread where I create a window which is going to be captured. The need for this thread comes from the need of having the message pump (blocking) in the same thread the window is created. I'm creating the window and notifying the other thread so a capture _item_ can be created there. Just after notifying, I start the message pump. If there is no delay between window creation and capture item then `E_INVALIDARG` is thrown from `CreateForWindow()`. If I add a sleep for about 250ms then the _item_ is created successfully. Running the code under the debugger also doesn't reproduce the issue, possibly because of timing effects. So it seems I have to run the message pump, and notify the other thread only after that which is impossible as the thread is blocked in the message pump. Replacing `std::thread` with `CreateThread()` doesn't make any difference.

**Comment by robmikh** [comment] 2022-03-22 15:32
We've identified a bug where CreateForWindow could could throw instead of returning E_INVALIDARG. This was fixed in Windows 11.

**Comment by nop144d** [comment] 2022-03-22 15:39
Is there any workaround for Windows 10? Or maybe my approach is completely wrong? Having sleeps in between is not correct, of course.

**Comment by nop144d** [comment] 2022-04-08 11:32
JFYI, I've noticed that `CreateForWindow()` returns `E_INVALIDARG` if the window that is to be captured hasn't processed any `WM_PAINT` message yet. Not sure if it's enough to process a single `WM_PAINT` message.

**Comment by robmikh** [comment] 2022-04-11 00:15
Unfortunately, I don't know of a great way to detect this. If that works for your purposes then I would go with it.

**Comment by robmikh** [comment] 2022-07-08 17:04
Thanks

**Comment by ZwergNaseXXL** [comment] 2022-12-19 09:52
I can confirm this issue for a few scenarios. In my app, I create a separate window in which I play back the stuff that I want to capture. But I don't want that window to appear in the taskbar, it's supposed to be "hidden". So I tried several things:
* Make the window owned by the config dialog from my app: CreateForWindow(HWND) returns E_INVALIDARG.
* Use the WS_EX_TOOLWINDOW style for the window: CreateForWindow(HWND) returns E_INVALIDARG.
* Remove the taskbar icon via the ITaskbarList interface: CreateForWindow(HWND) returns E_INVALIDARG.
CreateForWindow(HWND) works fine when I don't use any of the things above.

**Comment by nop144d** [comment] 2022-12-19 11:05
@ZwergNaseXXL see my question (and the workaround), hope that helps for hiding you window:
https://stackoverflow.com/questions/74347529/is-it-possible-to-create-and-capture-totally-invisible-hidden-window-using-windo

Still this needs to be officially supported!

**Comment by robmikh** [comment] 2022-12-19 18:29
Currently the only windows you can create GraphicsCaptureItems for are windows that would normally appear in the Alt+Tab menu. This is why took windows don't work for you. We are looking into expanding it but we have nothing to commit to at this time.

**Comment by nop144d** [comment] 2022-12-20 10:27
Thanks @robmikh , happy to hear that! As you can see, this is a common use case. Support for capturing tool windows would be a good addition to the functionality.

My original issue though, which still happens, is E_INVALIDARG for even _normal_ windows without tool style which are just created. I worked around it by delays and retries which in combination with unsetting and setting back the tool style results in a poor code as you can imagine.

**Comment by ZwergNaseXXL** [comment] 2023-02-07 17:50
So I've spent yet another fruitless day with trial-and-error... Could it be that the capture API also doesn't like windows in the maximized state? It's not the actual size itself, because when I set that same size programmatically, capturing works fine. But when I maximize the window via the maximize button, the borders are different. No left, right and bottom borders, just the caption. Similar to a tool window. And I guess that's the problem. 

Note that I move my capturing window to "hide" it, so that only one pixel is still in the visible area. This usually works for capturing the whole content, but with maximized windows only the visible part of the window is captured, the rest is black.

**Comment by robmikh** [comment] 2023-02-07 18:04
The capture API will capture windows just fine when maximized. But you may see differences in how different windows position and size themselves when maximized. This is usually the case with windows that draw their own non-client area (e.g. VS Code) vs more traditional windows (e.g. Regedit).

**Comment by ZwergNaseXXL** [comment] 2023-02-08 09:33
But it's the very same window in my case. In non-maximized ("restored") state, everything is captured. In maximized state, only the visible pixel is captured.

Of course, it would be even better if I wasn't forced to such shenanigans and capturing of properly hidden windows would just work. Like it does with the other capturing technologies, IE (obsolete) and WebView2 (too slow for video).

**Comment by robmikh** [comment] 2023-02-08 09:44
Unfortunately without a repro there's not much I can do.

**Comment by ZwergNaseXXL** [comment] 2023-02-08 13:44
Turns out this is related to another constraint of ours. Some video encoders demand that their input is evenly sized. So we have to mess with the window's client size on every resize, making sure that width and height are even. DX capture does not like it when the size of the captured window is different from the default size in maximized state. Was able to fix it by "restoring" the window to the monitor size instead of truly maximizing it.

**Comment by robmikh** [comment] 2023-02-08 18:51
Windows.Graphics.Capture does not require the size of the frame pool buffers to match the window. You can specify any size you want.

**Comment by robmikh** [comment] 2023-02-08 18:52
I'm going to close this issue as we're way off topic now. If you have any future problems, please file an issue with enough information where someone can assist you.

**Closed** 2023-02-08 18:52 UTC

**Comment by ZwergNaseXXL** [comment] 2023-02-19 17:34
Umm... Completed? Way off topic? 
I thought we were collecting issues here where minor window configuration changes like style or size changes would break the capture functionality. The current state is far from satisfactory and definitely not completed. People have put time and effort into detailing these issues for you. And even more time into finding workarounds. If you feel that this ticket here has become unmanagable, then please go ahead and create a new one with a short list of these issues. Just closing it and saying "go bother someone else" is not very professional.
