### ISSUE TITLE
Sometimes CreateCaptureItemForWindow throws fatal exception

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#43] opened 2019-09-28 20:10 UTC
After few attempts to call this code:
```cpp
auto activation_factory = winrt::get_activation_factory<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>();
auto interop_factory = activation_factory.as<IGraphicsCaptureItemInterop>();
winrt::Windows::Graphics::Capture::GraphicsCaptureItem item = { nullptr };
interop_factory->CreateForWindow(hwnd, winrt::guid_of<ABI::Windows::Graphics::Capture::IGraphicsCaptureItem>(), reinterpret_cast<void**>(winrt::put_abi(item)));
return item;
```

I get exception:
![image](https://user-images.githubusercontent.com/17680514/65821895-8051aa80-e244-11e9-8f88-699ed898c1ef.png)

And my code does not catch it.

It is very random. most of the time it happen after a lot of attempts to create the capture item.

Questions:

1. What can cause such exception and how to prevent it? Is there a common user mistake that cause this error?
2. How to handle the error? How to catch the error in case it happned? My code does not catch it. I don't want that the program will crash at the worst case scenario

Thanks.

**Comment by robmikh** [comment] 2019-10-02 07:53
Do you have a minimal version of the code that reproduces this error? Otherwise, please collect a process dump and we can take a look.

**Comment by gileli121** [comment] 2019-10-02 08:07
How to collect process dump with visual studio 2019?

**Comment by robmikh** [comment] 2019-10-02 08:16
Once you see the unhandled exception message from your screenshot, go to Debug->Save Dump As. Please make sure you select "Minidump with Heap" when saving.

**Comment by gileli121** [comment] 2019-10-02 08:25
OK, I will do it when it will happen again and upload here the dump.
Thanks

**Comment by robmikh** [comment] 2020-01-30 23:52
It's been a few months since any activity, so I'm going to close this issue. Please reopen it with the crash dump if you see it again.

**Closed by robmikh** 2020-01-30 23:52 UTC

**Comment by yjlintw** [comment] 2020-06-19 17:37
[Dmp file (Googld Drive)](https://drive.google.com/file/d/1DuZ1kJ10IE7t0VYBy-IFmXzca76VDbV1/view?usp=sharing)

I'm having the same problem. The dmp file is too big so I put it on google drive. Hope this will help.

**Comment by robmikh** [comment] 2020-06-19 20:38
Hey @yjlintw, do you have the same symptoms as the above? Looking at the dump, this won't be a failfast and should throw an exception that you should be able to catch. Are you able to do so?

For some reason I'm not able to recognize the error code that triggers the exception, not sure if there's an issue with the dump or there's some other issue going on. Are you able to reliably reproduce this error? Can you share more about the scenario? Is it always with a certain window? All windows? Does it ever succeed? 

We may need to get this reproducing locally to make progress.

**Comment by yjlintw** [comment] 2020-06-19 20:54
I don't have the try/catch statement initially. After adding that, I'm able to catch it.

It happens when I stop the capture and then start the capture again. It could happen to all windows, but it does not always happens. It happens every now and then.

My originally implementation was resizing the captured window -> stop capture -> start capture. I now resize the texture instead, which I think is a better implementation anyway, and it helps me get around this error.

**Comment by glemselenselv** [comment] 2020-07-29 09:11
I'm sorry to revive this kinda old thread, but I see similar fatal exceptions when I try to capture child windows or dialogs. I haven't read anything in the offical reference about whether the API supports top-level windows only so I wonder if this is even possible.

@robmikh, could you please confirm/deny my assumption?

**Comment by robmikh** [comment] 2020-07-29 20:13
That is to be expected. Thanks for a calling that out as far as the documentation goes, we should update it. We only support the capture of top level windows.

**Comment by EricBallard** [comment] 2021-08-04 03:41
Just an FYI - I was encountering this issue when trying to capture a window using DirectX 12, in the application settings - after changing to DirectX 11 (Legacy) I was able to capture the window without issue.

**Comment by robmikh** [comment] 2021-08-04 04:37
Correct, the `Direct3D11CaptureFramePool` does not support 11-on-12. We need to do some work to support Direct3D 12.

**Comment by tianyouhui** [comment] 2023-09-18 10:14
interop_factory->CreateForWindow() always crash while begin to capture window zoom->settings, is there something wrong?
![image](https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/assets/1204612/fb8927b5-a300-4bda-be06-cb58b1f100ba)

**Comment by robmikh** [comment] 2023-09-18 11:09
I'm guessing it's because the window is a tool window. The general rule of thumb is that if it's in alt+tab, you should be able to capture it.
