### ISSUE TITLE
Example cpp/ScreenCaptureforHWND not working - Unhandled exception at 0x00007FFD3B8B9129 (KernelBase.dll) in ScreenCaptureforHWND.exe

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#37] opened 2019-07-06 08:13 UTC
Hello, I tried to run the example
ScreenCaptureforHWND

Using Visual Studio 2019 on Windows 10 64bit with SDK 10.0.18362.0 

The example app was successfully built and working until I select some window to capture.

When I select a window, it always throws an exception 
![image](https://user-images.githubusercontent.com/17680514/60753674-fbf1e180-9fde-11e9-9c1a-f08b062f4090.png)

`Unhandled exception at 0x00007FFD3B8B9129 (KernelBase.dll) in ScreenCaptureforHWND.exe: 0xC000041D: An unhandled exception was encountered during a user callback.`

It is no matter what window I select. It always fails in this like.

Please fix the example.

Thank you.

**Comment by gileli121** [comment] 2019-07-06 16:53
It tried to load some class from this file that provided with the SDK
![image](https://user-images.githubusercontent.com/17680514/60759076-a261d500-a027-11e9-900b-6dc0c8659687.png)

And Visual Studio reports some small error in this file. 
It looks like something is wrong with this file that provided with the SDK

**Comment by robmikh** [comment] 2019-07-07 05:44
It seems that you're failing the QI to get the IGraphicsCaptureItemInterop interface. Which version of Windows are you running? This feature was added in the 1903 update.

**Comment by gileli121** [comment] 2019-07-07 07:43
I have OS Build 10.0.17763.557 
I will try it again after updating and will let you know if the issue resolved

**Comment by gileli121** [comment] 2019-07-07 23:15
Hello, after I updated the example works. Good. is there an otption to not capture the mouse pointer?

And now I have another issue with the API function DwmRegisterThumbnail from here:
https://answers.microsoft.com/en-us/windows/forum/windows_10-update/dwmregisterthumbnail-is-not-working-as-expected-in/72dcf82e-7e8e-46f6-b7f3-d80f6f34fefa?tm=1562540172919

My program makes some big use with this function and after this update the function is not working as expected. Please see the issue I reported to Microsoft:

https://answers.microsoft.com/en-us/windows/forum/windows_10-update/dwmregisterthumbnail-is-not-working-as-expected-in/72dcf82e-7e8e-46f6-b7f3-d80f6f34fefa?tm=1562540172919

I know that the issue is not related to this. I just don't know where to get the support. 
Please let me know where to get support about this issue. I am not sure that I reported it in the right place.

The issue is big and it broke something in my program... 
Please help me to get support about this. 

Thanks

**Comment by robmikh** [comment] 2019-07-08 03:49
Glad to hear the sample is working. The current Insider builds have an API we plan to add that makes the cursor rendering configurable. Look for a new property on `GraphicsCaptureSession` named `IsCursorCaptureEnabled`.

As for your issue with DwmRegisterThumbnail, what exactly are you having a problem with? Multiple thumbnails that are assigned to a single window, or the same thumbnail (or at least thumbnails targeting the same window) across multiple windows? I tried both just now and couldn't reproduce any issues. What would I do to reproduce this?

**Comment by gileli121** [comment] 2019-07-08 07:07
Hello, I think that the problem is when you use the API via DLL file.. I could reproduce the bug only by using the API from script that written in Autoit.

Please try to run this code:
`#include-once
#include <WinAPIConstants.au3>

Global Const $DWM_TNP_RECTDESTINATION = 0x00000001
;~ Global Const $DWM_TNP_RECTSOURCE = 0x00000002
Global Const $DWM_TNP_OPACITY = 0x00000004
Global Const $DWM_TNP_VISIBLE = 0x00000008
Global Const $DWM_TNP_SOURCECLIENTAREAONLY = 0x00000010



HotKeySet('{ESC}',Exit1)
Func Exit1()
	Exit
EndFunc

$targetGUI = HWnd(0x000000000002004C)

$hGUI1 = GUICreate('Preview 1',400,400)
GUISetState(@SW_SHOW,$hGUI1)
$handle1 = RegisterWindowLivePreview($targetGUI,$hGUI1)


$hGUI2 = GUICreate('Preview 2',400,400)
GUISetState(@SW_SHOW,$hGUI2)
$handle2 = RegisterWindowLivePreview($targetGUI,$hGUI2)


While 1
	Sleep(100)
WEnd



Func RegisterWindowLivePreview($hWindow,$hLivePreviewGui, $iClientAreaOnly = False, $iLivePreviewWidth = Default, $iLivePreviewHeight = Default, _
										$iLivePreviewRectX = 0, $iLivePreviewRectY = 0)


	If $iLivePreviewWidth = Default Or $iLivePreviewHeight = Default Then

		Local $aPos = WinGetPos($hLivePreviewGui)
		If @error Then
			ConsoleWrite("Can't get size of the GUI where the live preview will be draw." & @CRLF)
			Return SetError(1)
		EndIf

		If $iLivePreviewWidth = Default Then $iLivePreviewWidth = $aPos[2]
		If $iLivePreviewHeight = Default Then $iLivePreviewHeight = $aPos[3]

	EndIf

	Local $hDwmLivePreviewHandle = _DWM_Thumbnail_Register($hLivePreviewGui, $hWindow)
	If @error Then
		ConsoleWrite("Registration of Thumbnail failed." & @CRLF)
		Return SetError(2)
	EndIf
	ConsoleWrite($hDwmLivePreviewHandle & @CRLF)
	If Not _DwmQueryThumbnailSourceSize($hDwmLivePreviewHandle) Then
		ConsoleWrite("Thumbnail Source Size could not be determined." & @CRLF)
		_DWM_Thumbnail_Unregister($hDwmLivePreviewHandle)
		Return SetError(3)
	EndIf

	_DWM_Thumbnail_Update_Properties($hDwmLivePreviewHandle, $iLivePreviewRectX, $iLivePreviewRectY, $iLivePreviewWidth, $iLivePreviewHeight)
	If @error Then
		ConsoleWrite("Failed to _DWM_Thumbnail_Update_Properties" & @CRLF)
		_DWM_Thumbnail_Unregister($hDwmLivePreviewHandle)
		Return SetError(4)
	EndIf

	Return $hDwmLivePreviewHandle

EndFunc




Func _DWM_Thumbnail_Register($hwnd, $hWndOw)

	$tID = DllStructCreate('dword')
	$aRet = DllCall("dwmapi.dll", "int", "DwmRegisterThumbnail", "hwnd", $hwnd, "hwnd", $hWndOw, "ptr*", DllStructGetPtr($tID))
	If Not IsArray($aRet) Then
		Return SetError(1, 0, 0) ; Register thumbnail failed
	EndIf

	Return $aRet[3]
EndFunc   ;==>_DWM_Thumbnail_Register



Func _DwmQueryThumbnailSourceSize($hThumbID)
	#cs
		http://msdn.microsoft.com/en-us/library/aa969520%28VS.85%29.aspx
		HRESULT DwmQueryThumbnailSourceSize(
		HTHUMBNAIL hThumbnail,
		PSIZE pSize
		);
		typedef struct tagSIZE {
		LONG cx;
		LONG cy;
		}SIZE, *PSIZE;
	#ce

	$tSize = DllStructCreate("int X;int Y")
	$aRet = DllCall("dwmapi.dll", "hwnd", "DwmQueryThumbnailSourceSize", "hwnd", $hThumbID, "ptr", DllStructGetPtr($tSize))


	If IsArray($aRet) And $aRet[0] = $S_OK Then
		$i_hwnd_Thumbnail_Width = DllStructGetData($tSize, 1)
		$i_hwnd_Thumbnail_Height = DllStructGetData($tSize, 2)
		Return True
	Else

;~ 		if Not IsArray($aRet) Then
;~ 			_FileWriteLog('WindowTopLog.log', "DwmAPI.au3 - L45 - _DwmQueryThumbnailSourceSize - $aRet is not array - return false")
;~ 		Else
;~ 			_FileWriteLog('WindowTopLog.log', "DwmAPI.au3 - L47 - _DwmQueryThumbnailSourceSize - $aRet[0] = " & $aRet[0])
;~ 		EndIf
		Return False
	EndIf
EndFunc   ;==>_DwmQueryThumbnailSourceSize

Func _DWM_Thumbnail_Update_Properties($hThumbID, $rcDest_X, $rcDest_Y, $rcDest_Width, $rcDest_Height, $rcOpacity = 255, $rcReadOnly = True, $rcClientAreaOnly = 0)


	$tDWM_THUMBNAIL_PROPERTIES = DllStructCreate("dword dwFlags;int rcDestination[4];int rcSource[4];byte opacity;int fVisible;int fSourceClientAreaOnly")

	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "dwFlags", BitOR($DWM_TNP_RECTDESTINATION, $DWM_TNP_OPACITY, $DWM_TNP_VISIBLE, $DWM_TNP_SOURCECLIENTAREAONLY))
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "rcDestination", $rcDest_X, 1)
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "rcDestination", $rcDest_Y, 2)
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "rcDestination", $rcDest_Width, 3)
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "rcDestination", $rcDest_Height, 4)
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "opacity", $rcOpacity)
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "fVisible", $rcReadOnly)
	DllStructSetData($tDWM_THUMBNAIL_PROPERTIES, "fSourceClientAreaOnly", $rcClientAreaOnly)

	$pDWM_THUMBNAIL_PROPERTIES = DllStructGetPtr($tDWM_THUMBNAIL_PROPERTIES)

	$aRet = DllCall("dwmapi.dll", "int", "DwmUpdateThumbnailProperties", "ptr", $hThumbID, "ptr", $pDWM_THUMBNAIL_PROPERTIES)
	If Not IsArray($aRet) Then

		Return SetError(1, 0, 0) ; Update thumbnail failed
	EndIf

	;_ArrayDisplay($aRet, "DwmAPI.au3 - L80 - aRet array")

EndFunc   ;==>_DWM_Thumbnail_Update_Properties

Func _DWM_Thumbnail_Unregister($hThumbID)

	$aRet = DllCall("dwmapi.dll", "int", "DwmUnregisterThumbnail", "hwnd", $hThumbID)
	If Not IsArray($aRet) Then

		Return SetError(1, 0, 0) ; Unregister thumbnail failed
	EndIf

	Return $aRet[0]
EndFunc   ;==>_DWM_Thumbnail_Unregister


`

The problem is that you will see only one window getting the live preview. it did not happned before the update.

This is how it looks:
![image](https://user-images.githubusercontent.com/17680514/60789288-7188b980-a167-11e9-8842-9e23ab23812e.png)

The preview 2 window don't get a live preview. Only the first one.
If I will  remove this line that create the first preview:
`$handle1 = RegisterWindowLivePreview($targetGUI,$hGUI1)`

The second preview will work.

I think that the problem is because the API returns the same HTHUMBNAIL twice.
The this line:
`$aRet = DllCall("dwmapi.dll", "int", "DwmRegisterThumbnail", "hwnd", $hwnd, "hwnd", $hWndOw, "ptr*", DllStructGetPtr($tID))`
Will call to this function. the function returns the ID 1 even the second time. I think that this is the bug..
But in C++ version I did not saw this. The ID was 2 on the second call and not 1.

**Comment by gileli121** [comment] 2019-07-08 07:20
It seems that you did some change in dwmapi.dll in this update.
It seems that this dll now stores some global memory for the HTHUMBNAIL  ID.

I know this because I found the solution. 
The solution is open the dll file using:
`$dwmDll = DllOpen('dwmapi.dll')`

And then in any line that calls the dll, I need to use the dll handle `$dwmDll` 
So instead of
`DllCall('dwmapi.dll', ... `
I write 
`DllCall($dwmDll, ... `

This was solved the issue and now the script print different HTHUMBNAIL on the second call as expected.

**Comment by robmikh** [comment] 2019-07-08 17:06
That seems like there was a behavior change in Autoit, I can't get this to happen in C++. Glad everything was sorted out for you.

**Closed by robmikh** 2019-07-08 17:06 UTC

**Comment by krenner** [comment] 2019-07-11 18:45
Hi gileli121 - I wanted to comment on your question re: mouse cursors.  Insider preview builds 18894 or greater have a new  property on GraphicsCaptureSession named IsCursorCaptureEnabled.  Release notes are [here](https://blogs.windows.com/windowsdeveloper/2019/05/14/windows-10-sdk-preview-build-18894-available-now/#dxC8joQ4Jtk2fwMp.97).

**Comment by gileli121** [comment] 2019-07-11 22:42
Thanks. 
Will be also an option to remove the yellow frame of the window that under capture mode?

**Comment by robotogre** [comment] 2021-01-23 05:14
@robmikh I am seeing this error in the latest version of Windows 10 LTSC 1809 (17763.1728). 

Am I out of luck?
