### ISSUE TITLE
Can't use IsCursorCaptureEnabled from C# even after I did com import myself for IGraphicsCaptureSession2

### ISSUE THREAD

**Issue by gileli121** [microsoft/Windows.UI.Composition-Win32-Samples#97] opened 2022-01-14 18:51 UTC
Hello, 
For some reason, `IGraphicsCaptureSession2` and `IGraphicsCaptureSession3` are not available in C# but it is available in the docs here
https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.iscursorcaptureenabled?view=winrt-22000

I was able to manually import this part myself - 

I found this part in `windows.graphics.capture.h`
```cpp
...
...
extern const __declspec(selectany) _Null_terminated_ WCHAR InterfaceName_Windows_Graphics_Capture_IGraphicsCaptureSession2[] = L"Windows.Graphics.Capture.IGraphicsCaptureSession2";
namespace ABI {
    namespace Windows {
        namespace Graphics {
            namespace Capture {
                MIDL_INTERFACE("2c39ae40-7d2e-5044-804e-8b6799d4cf9e")
                IGraphicsCaptureSession2 : public IInspectable
                {
                public:
                    virtual HRESULT STDMETHODCALLTYPE get_IsCursorCaptureEnabled(
                        boolean* value
                        ) = 0;
                    virtual HRESULT STDMETHODCALLTYPE put_IsCursorCaptureEnabled(
                        boolean value
                        ) = 0;
                };

                extern MIDL_CONST_ID IID& IID_IGraphicsCaptureSession2 = _uuidof(IGraphicsCaptureSession2);
            } /* Capture */
        } /* Graphics */
    } /* Windows */
} /* ABI */
....
....
``` 

So took the example here:
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/tree/master/dotnet/WPF/ScreenCapture
And under `CaptureSampleCore` I created this class:

```c#
namespace CaptureSampleCore.ComImports
{
    [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("2c39ae40-7d2e-5044-804e-8b6799d4cf9e")]
    [System.Security.SuppressUnmanagedCodeSecurity]
    public interface IGraphicsCaptureSession2
    {
        bool IsCursorCaptureEnabled { get; set; }
    }
}
```

Next, in file:
https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/blob/master/dotnet/WPF/ScreenCapture/CaptureSampleCore/BasicCapture.cs#L94

I added the following code:
```c#
public void StartCapture()
{
	// New Code - Start
	var pUnk = Marshal.GetIUnknownForObject(session);
	var session2 = Marshal.GetObjectForIUnknown(pUnk) as IGraphicsCaptureSession2;
	session2.IsCursorCaptureEnabled = false;
	// New Code - End
	
	session.StartCapture();
}
```

I did debug and found that it actually try to work because it was able to get `session2` object and the debugger shows 2 properties that are `true`. It means that something until this point worked fine - it was able to cast it to `IGraphicsCaptureSession2` and also read these properties:
![image](https://user-images.githubusercontent.com/17680514/149568776-c067814d-faf0-4cde-801e-67c58aee1f5e.png)

It even show extra property called `IsBorderRequired`. It is documented in the docs and I want to use it also.. but not for now.
I don't know how it printed it because `IGraphicsCaptureSession2` should not have it.. `IGraphicsCaptureSession3` have it..

The program will crash when it will execute this line that it tries to set the value of `IsCursorCaptureEnabled` to `false`:
![image](https://user-images.githubusercontent.com/17680514/149569569-571aad28-f912-4c76-9e63-42c28d896875.png)

Any idea what I am doing wrong here?

Thanks

**Comment by gileli121** [comment] 2022-01-14 20:02
COOL !!
I did it!
My mistake was here:
![image](https://user-images.githubusercontent.com/17680514/149577616-d9e9169b-63e8-48c6-962f-ee127a761d2d.png)

It should be:
```c#
ComInterfaceType.InterfaceIsIInspectable
```

I found it by looking on `windows.graphics.capture.h` 
![image](https://user-images.githubusercontent.com/17680514/149577783-5a98dd69-80ca-4ec9-97c4-e51f0891128b.png)


Now it works perfect!

**Comment by gileli121** [comment] 2022-01-14 20:13
This will disable the border!!

1. Add:
```c#
[ComImport]
[InterfaceType(ComInterfaceType.InterfaceIsIInspectable)]
[Guid("f2cdd966-22ae-5ea1-9596-3a289344c3be")]
public interface IGraphicsCaptureSession3
{
	bool IsBorderRequired { get; set; }
}
```

2. Add the following code after you have `session` object and before the call to  `session.StartCapture();` :

```c#
var pUnk = Marshal.GetIUnknownForObject(session);
var session3 = Marshal.GetObjectForIUnknown(pUnk) as IGraphicsCaptureSession3;
session3.IsBorderRequired = false;
```

**Comment by robmikh** [comment] 2022-01-19 00:36
I'm going to close this as you seem to have it figured out. To recap, all WinRT interfaces inherit from IInspectable, so keep that in mind when crafting those interface definitions by hand. I would recommend looking at the [CsWinRT](https://github.com/microsoft/cswinrt) project to have them generated from metadata instead. 

Second, a comment on the usage of the [IsBorderRequired](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-22000) property. Before accessing this property, you should call [GraphicsCaptureAccess.RequestAccessAsync](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureaccess.requestaccessasync?view=winrt-22000#windows-graphics-capture-graphicscaptureaccess-requestaccessasync(windows-graphics-capture-graphicscaptureaccesskind)) and request access to the border. This doesn't make a huge difference for unpackaged Win32 applications, but is critical for packaged applications. Even if you are writing an unpackaged application, I still suggest calling it [as it is the documented requirement](https://devblogs.microsoft.com/oldnewthing/20080925-00/?p=20763).

**Closed by robmikh** 2022-01-19 00:36 UTC

**Comment by gileli121** [comment] 2022-01-19 22:26
> I'm going to close this as you seem to have it figured out. To recap, all WinRT interfaces inherit from IInspectable, so keep that in mind when crafting those interface definitions by hand. I would recommend looking at the [CsWinRT](https://github.com/microsoft/cswinrt) project to have them generated from metadata instead.
> 
> Second, a comment on the usage of the [IsBorderRequired](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-22000) property. Before accessing this property, you should call [GraphicsCaptureAccess.RequestAccessAsync](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscaptureaccess.requestaccessasync?view=winrt-22000#windows-graphics-capture-graphicscaptureaccess-requestaccessasync(windows-graphics-capture-graphicscaptureaccesskind)) and request access to the border. This doesn't make a huge difference for unpackaged Win32 applications, but is critical for packaged applications. Even if you are writing an unpackaged application, I still suggest calling it [as it is the documented requirement](https://devblogs.microsoft.com/oldnewthing/20080925-00/?p=20763).
> 
> EDIT: One more thing, it's safe to modify the IsBorderRequired property even if RequestAccessAsync says you don't have access. That just means the user preference or the system policy is currently set so that the border will always show up. But if it changes, the system will reevaluate using the value you placed in IsBorderRequired.

#robmikh 
My project is Win32 app / WPF app that packaged as Microsoft Store app using this method:
https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net
I tested it also while it is installed as "UWP" app and it worked fine without GraphicsCaptureAccess.RequestAccessAsync 

So I don't understand why it is matters at all anyway.

**Comment by robmikh** [comment] 2022-01-19 22:44
Please just follow the documentation. Your app may break in the future, even if it appears to not do anything today.

**Comment by gileli121** [comment] 2022-01-20 00:20
@robmikh 
So you saying that the fact that it works for packaged app is bug? My app is declared wtih capability `runFullTrust` so I don't think that it is bug. 

This is the part about capabilities in my packaged app:
```xml

  <Applications>
    <Application Id="App"
      Executable="$targetnametoken$.exe"
      EntryPoint="$targetentrypoint$">
      <uap:VisualElements
        DisplayName="WindowTop"
        Description="UWP_PackagingProject"
        BackgroundColor="transparent"
        Square150x150Logo="Images\Square150x150Logo.png"
        Square44x44Logo="Images\Square44x44Logo.png">
        <uap:DefaultTile Wide310x150Logo="Images\Wide310x150Logo.png"  Square71x71Logo="Images\SmallTile.png" Square310x310Logo="Images\LargeTile.png"/>
        <uap:SplashScreen Image="Images\SplashScreen.png" />
        <uap:InitialRotationPreference>
          <uap:Rotation Preference="landscape"/></uap:InitialRotationPreference>
      </uap:VisualElements>

      <Extensions>
        <desktop:Extension
          Category="windows.startupTask"
          Executable="WindowTop\WindowTop.exe"
          EntryPoint="Windows.FullTrustApplication">
          <desktop:StartupTask
            TaskId="WindowTopStartupTask"
            Enabled="false"
            DisplayName="Start WindowTop with Windows" />
        </desktop:Extension>
      </Extensions>
    </Application>
  </Applications>

  <Capabilities>
    <Capability Name="internetClient" />
    <rescap:Capability Name="runFullTrust" />
  </Capabilities>
```

If I will call to GraphicsCaptureAccess.RequestAccessAsync, it will open dialog for the user (assuming that I added `graphicsCaptureWithoutBorder` capability) and the user will need to accept it?

**Comment by robmikh** [comment] 2022-01-20 01:34
If you're running full trust, that would explain not seeing anything from RequestAccessAsync (although, again, you should still call it).

In the event that you would get a prompt, it would be a one time prompt to the user. All other times it would return the user's selected preference. This is similar to the way GPS or camera capabilities work.

**Comment by gileli121** [comment] 2022-01-20 02:32
> If you're running full trust, that would explain not seeing anything from RequestAccessAsync (although, again, you should still call it).

OK, the current behavior considered as bug?
And I should not get a prompt after `RequestAccessAsync` in case of full trust package?

**Comment by robmikh** [comment] 2022-01-20 02:56
Not a bug, and yes I wouldn't expect the prompt to show up. 

_If_ that changes in the future, it would only be a prompt the user sees once for the duration that your application is installed.

**Comment by gileli121** [comment] 2022-01-21 13:06
Thank you @robmikh
So if it is not bug, I am not going to use `GraphicsCaptureAccess.RequestAccessAsync` even if it suggested because it works and `if it works, don't break it`. 

And another question: How I can check if this property `IsBorderRequired` is available in the system? 
I can try to warp it in try-catch block but maybe there is better way

**Comment by robmikh** [comment] 2022-01-21 16:03
That's a bad idea. 

Use ApiInformation:

https://docs.microsoft.com/en-us/uwp/api/windows.foundation.metadata.apiinformation.ispropertypresent?view=winrt-22000
