### ISSUE TITLE
Render captured screen to a WPF BitmapImage?

### ISSUE THREAD

**Issue by NickThissen** [microsoft/Windows.UI.Composition-Win32-Samples#41] opened 2019-08-18 11:39 UTC
Is it possible to grab the captured screen "texture" and render it to a BitmapImage in memory?

Here is some context on what I want to do and what I tried already.

I am trying to capture the contents of a WPF Window (not UWP) and convert it to a BitmapImage, specifically a System.Windows.Media.Imaging.BitmapImage (WPF). This BitmapImage then allows me to send the pixel data over a network for display on another PC. I would like to do this in real-time around 60 frames per second.

At the moment, in WPF, I am using the RenderTargetBitmap.Render(Visual) method. It works and is very easy, but it is simply not fast enough to reach 60 fps. If the visual tree becomes even somewhat complex it slows down to below 5 fps.

I found this new UWP composition Screen Capture sample which looks promising, as it is able to capture the same WPF window very smoothly. If I can somehow "grab" the captured image and get the raw pixels, then perhaps I can use this as an alternative to WPF RenderTargetBitmap.

I believe the place to "hook in" would be in the BasicCapture class, where the texture is being copied:

                using (var backBuffer = swapChain.GetBackBuffer<SharpDX.Direct3D11.Texture2D>(0))
                using (var bitmap = Direct3D11Helper.CreateSharpDXTexture2D(frame.Surface))
                {
                    d3dDevice.ImmediateContext.CopyResource(bitmap, backBuffer);

                    // My addition:
                    GetBitmap(bitmap);
                }

The big question now is: how do I convert this Texture2D to a "raw pixel data" or preferably BitmapImage that I can further consume in my WPF app?

With my current "GetBitmap" code, I am able to write the image to a file on disk:

       private void GetBitmap(Texture2D texture)
        {
            // Create texture copy
            var copy = new Texture2D(d3dDevice, new Texture2DDescription
            {
                Width = texture.Description.Width,
                Height = texture.Description.Height,
                MipLevels = 1,
                ArraySize = 1,
                Format = texture.Description.Format,
                Usage = ResourceUsage.Staging,
                SampleDescription = new SampleDescription(1, 0),
                BindFlags = BindFlags.None,
                CpuAccessFlags = CpuAccessFlags.Read,
                OptionFlags = ResourceOptionFlags.None
            });

            // Copy data
            d3dDevice.ImmediateContext.CopyResource(texture, copy);

            var dataBox = d3dDevice.ImmediateContext.MapSubresource(copy, 0, 0, MapMode.Read, MapFlags.None,
                out DataStream stream);
            var rect = new DataRectangle
            {
                DataPointer = stream.DataPointer,
                Pitch = dataBox.RowPitch
            };

            var format = PixelFormat.Format32bppPBGRA;
            Bitmap bmp = new Bitmap(factory, copy.Description.Width, copy.Description.Height, format, rect);

            using (var wic = new WICStream(factory, "test_output.png", NativeFileAccess.ReadWrite))
            using (var encoder = new PngBitmapEncoder(factory, wic))
            using (var frame = new BitmapFrameEncode(encoder))
            {
                frame.Initialize();
                frame.SetSize(bmp.Size.Width, bmp.Size.Height);
                frame.SetPixelFormat(ref format);
                frame.WriteSource(bmp);
                frame.Commit();
                encoder.Commit();
            }

            d3dDevice.ImmediateContext.UnmapSubresource(copy, 0);
            copy.Dispose();
            bmp.Dispose();
        }
    }

This addition seems to add about 20-40 ms of delay each frame, which is a bit much, but I'm hopeful a large part of that is actually saving the file. I don't need to save the file to disk, I just need it in memory so I can get the pixel data.

I tried using a InMemoryRandomAccessStream and creating a UWP BitmapImage from that, but there is a threading issue and it does not allow me to create a BitmapImage in this code. Even if I could, I don't see a way to convert the UWP BitmapImage to my WPF BitmapImage which I require.

To clarify, in the end what I need is to use the BitmapSource.CopyPixels method:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.bitmapsource.copypixels?view=netframework-4.8#System_Windows_Media_Imaging_BitmapSource_CopyPixels_System_Windows_Int32Rect_System_IntPtr_System_Int32_System_Int32_

This allows me to copy the pixels on a BitmapSource to the right memory location where it is being send over the network. 

If I can somehow get this pixel data without going through a BitmapImage that is fine too, I simply cannot find a way.

Does anyone see a way to make this possible or am I chasing an impossible dream?

**Comment by NickThissen** [comment] 2019-08-18 19:54
I got a little further and was able to capture the recorded screen as a Stream in memory. I then send the Stream to my NDI sender client which converts it to a WPF BitmapImage, and it finally uses CopyPixels to copy the pixels into the relevant memory address.

This way I am able to:
- Use the Screen Capture to capture my application window into a memory stream
- Use NDI to send the pixel data over the network and view it on an NDI monitor.

Unfortunately I am unable to transmit transparency at the moment. It seems the screen capture is not capturing transparency. The WPF window I am trying to capture is completely transparent (except for the visible elements), but in the screen capture it turns out with a black background. 

I have been playing with the various pixel formats but nothing seems to help. 

Is it possible to capture a transparent window and keep the transparency alive, including semi-transparent elements?


This is my updated GetBitmap code. It turns the Texture2D into a Bitmap, then encodes it into a Stream using WICStream and PngBitmapEncoder. The Stream is finally sent to my NDI client via the BitmapCaptured event, remaining code is not relevant at this time I think.

        private void GetBitmap(Texture2D texture)
        {
            // Create texture copy
            var copy = new Texture2D(d3dDevice, new Texture2DDescription
            {
                Width = texture.Description.Width,
                Height = texture.Description.Height,
                MipLevels = 1,
                ArraySize = 1,
                Format = texture.Description.Format,
                Usage = ResourceUsage.Staging,
                SampleDescription = new SampleDescription(1, 0),
                BindFlags = BindFlags.None,
                CpuAccessFlags = CpuAccessFlags.Read,
                OptionFlags = ResourceOptionFlags.None
            });

            // Copy data
            d3dDevice.ImmediateContext.CopyResource(texture, copy);

            var dataBox = d3dDevice.ImmediateContext.MapSubresource(copy, 0, 0, MapMode.Read, MapFlags.None,
                out DataStream stream);
            var rect = new DataRectangle
            {
                DataPointer = stream.DataPointer,
                Pitch = dataBox.RowPitch
            };
            
            var format = PixelFormat.Format32bppPBGRA;
            Bitmap bmp = new Bitmap(factory, copy.Description.Width, copy.Description.Height, format, rect);
            
            using (var ras = new InMemoryRandomAccessStream())
            {
                var ms = ras.AsStream(); // Do not dispose here
                using (var wic = new WICStream(factory, ms))
                using (var encoder = new PngBitmapEncoder(factory, wic))
                using (var frame = new BitmapFrameEncode(encoder))
                {
                    frame.Initialize();
                    frame.SetSize(bmp.Size.Width, bmp.Size.Height);
                    frame.SetPixelFormat(ref format);
                    frame.WriteSource(bmp);
                    frame.Commit();
                    encoder.Commit();
                }

                BitmapCaptured?.Invoke(this, new CaptureEventArgs(ms, bmp.Size.Width, bmp.Size.Height));
            }

            d3dDevice.ImmediateContext.UnmapSubresource(copy, 0);
            copy.Dispose();
            bmp.Dispose();
        }

To get transparency to work I was trying to change the various formats in the constructor of BasicCapture like here:

        public BasicCapture(IDirect3DDevice d, GraphicsCaptureItem i, BitmapImage im)
        {
            item = i;
            device = d;
            d3dDevice = Direct3D11Helper.CreateSharpDXDevice(device);

            factory = new ImagingFactory();

            var dxgiFactory = new SharpDX.DXGI.Factory2();
            var description = new SharpDX.DXGI.SwapChainDescription1()
            {
                Width = item.Size.Width,
                Height = item.Size.Height,
                Format = SharpDX.DXGI.Format.B8G8R8A8_UNorm,
                Stereo = false,
                SampleDescription = new SharpDX.DXGI.SampleDescription()
                {
                    Count = 1,
                    Quality = 0
                },
                Usage = SharpDX.DXGI.Usage.RenderTargetOutput,
                BufferCount = 2,
                Scaling = SharpDX.DXGI.Scaling.Stretch,
                SwapEffect = SharpDX.DXGI.SwapEffect.FlipSequential,
                AlphaMode = SharpDX.DXGI.AlphaMode.Premultiplied,
                Flags = SharpDX.DXGI.SwapChainFlags.None
            };
            swapChain = new SharpDX.DXGI.SwapChain1(dxgiFactory, d3dDevice, ref description);

            framePool = Direct3D11CaptureFramePool.Create(
                device,
                DirectXPixelFormat.B8G8R8A8UIntNormalized,
                2,
                i.Size);
            session = framePool.CreateCaptureSession(i);
            lastSize = i.Size;

            framePool.FrameArrived += OnFrameArrived;
        }

Am I going in the right direction or is transparency simply not supported?

**Comment by robmikh** [comment] 2019-09-25 04:29
Hi @NickThissen, sorry about the late reply.

We have a bug in Version 1903 where transparency wasn't working right due to a clearing issue. This will be fixed in the next release (the fix is in the Insider Fast builds). 

However, you should know that a transparent window will appear in the frame the same way as it does in the picker: it will not contain the contents behind the window. This is because we do a separate render pass of the window/monitor. A separate render pass allows us to avoid problems with the window being occluded, but it also means that it loses its context from the desktop.

What's the scenario you have in mind?

**Comment by gileli121** [comment] 2019-09-25 05:12
Hello, I am using this bug for what I did.
Please add an option to keep this "bug" if the developer want.

I created transparency efffect that the window is transparent but not the texts inside.

For this I need to:
1) Hide the window by making it transparent
2) Capture the window and get the frame without the transparency
3) Procces the frame using algorithem:
* Detect any pixel in the frame that is shape or image
* Remove any pixel in the frame that is not shape or image(remove background pixels)
4) Draw the frame above the window with the transparency 


I used what you call "bug" for making this possible and worked in it very hard.

Please add an option in the API to allow ignoring transparency and the option disabled by default.

Thanks

**Comment by NickThissen** [comment] 2019-09-25 06:55
Hello @robmikh

That sounds exactly what I need! I do not want to capture the desktop, I only want the contents of my window, and wherever my window is transparent I want the output of the capture the be transparent as well, e.g. If I save it as a png transparency should be kept.

At the moment I use WPF RenderTargetBitmap which does exactly this but is very slow for large windows, even if 99% of the window is empty.

**Comment by gileli121** [comment] 2019-09-25 08:43
And this is exactly what I *dont't* need!
Please add option in the API to capture without transparency also. 

Some developers may need to ignore transparency.

You never know hou much the use case on your API can be creative so please try to provide the most flexible API 

This bug should be a feature that maybe should disabled by default because maybe it is not the common use case. But please don't fix it without having option to enable it back.

I sent you email to ‏‪WinComposition@microsoft.com‬‏

About the request

**Comment by NickThissen** [comment] 2019-09-25 10:47
@gileli121 Obviously it is not my intention to take away functionality. If possible yes it should be optional either as a setting or just in the way you process the captured frames.

That said, I don't see why you need to keep this bug in place. It sounds like you're removing the background pixels manually in order to create the transparency on pixels where your own content is not visible. Isn't that exactly what a true transparency would achieve automatically? With the additional bonus that you can get semi-transparent visuals?

**Comment by gileli121** [comment] 2019-09-25 11:06
@NickThissen
I am creating a utility that have the option make any program to be transparent like this... So I can't do it 100% natively. It must done the hard way

There is no "my own content" in thid case

**Comment by NickThissen** [comment] 2019-09-25 14:29
@gileli121 Ok I see.

However, I still don't understand why fixing the bug would break your workflow. You will just get a truly transparent background instead of a black background. If you add that transparent image on top of a fully black rectangle, you have exactly the same situation as now. 

But let's not take this too far off-topic.

**Comment by gileli121** [comment] 2019-09-25 15:08
The flow:
1) Change window to be transparent
http://prntscr.com/pauuwp
2) Create child transparent window with the same size and position and with click-through style
3) Capture notepad.exe window using the API wile notepad.exe is transparent
4) Process the frame
5) Draw the frame above notepad.exe window

Result:
http://prntscr.com/paux0b

If I can't capture a transparent window, I can't do this.

I hope it answers the question

**Comment by robmikh** [comment] 2019-09-25 20:58
Hi @gileli121, @NickThissen is correct. You should be able to get the same thing as the old behavior by blending the frame you get back from the API with a black texture of the same size/pixel format.

We'll take your feedback into account, we'll look into exposing a clear color property in the API. However, it's too late for the next release for us to add such an API, so I can't make any promises.

It looks like the original issues has been resolved, so I'm going to go ahead and close this one. Feel free to open a new issue if there's a problem you'd like to discuss.

**Closed by robmikh** 2019-09-25 20:58 UTC

**Comment by gileli121** [comment] 2019-09-25 21:09
Thanks! Can we continue the discussion via your github email?
I will appreciate help of some explanation how I disable the transparency after the API returned the frame with the transparency. You say that I should modify the alpha channel?

And please take your time and I strongly recommend you to add this capability (capture as if the window is not transparent to the API.
I will very appreciate it!

Thanks.

**Comment by NickThissen** [comment] 2019-10-02 22:13
@robmikh
I finally managed to install W10 insider build on a VM today and can confirm the transparency is now working! Did not require any additional changes, it just works now as I expected. Thanks for the tip. 

I did notice that performance was not that great at the moment, feels like maybe 30 FPS and I'm aiming for 60. I am hopeful this is cause it's running in a rather slow VM and when it runs on a normal (powerful) PC it is better. But I don't have another PC like that lying around to test it on... 

Do you have any idea when the release with this update can be expected outside of the insider builds?

**Comment by robmikh** [comment] 2019-10-03 00:29
I'm glad that it's working for you!

Try to add another CPU core to the VM if you can, that might help. Unless you've configured it differently, the VM is probably running on a software adapter which will cause contention for CPU resources with the rest of the system. It will be even worse on a single core VM. The amount of RAM you've allocated and your disk speed might impact this too, if the OS is constantly running to the page file.

Unfortunately I don't have a timeline for when this release actually ships. If that information becomes available, I'll be sure to reply back here.

**Comment by Zofware** [comment] 2019-12-01 19:13
@robmikh, will this forthcoming transparency fix also apply to graphics capture in UWP apps? I'm having the same problem as @NickThissen but in my UWP app. I'm trying to capture some transparent elements but the captured image only contains opaque pixels (i.e. the transparency is lost). Thanks!

**Comment by robmikh** [comment] 2019-12-02 02:25
That's correct. Both Win32 and UWP apps will see the fixed behavior.

**Comment by NickThissen** [comment] 2020-01-21 20:41
Sorry to drag up this old topic.

Today I updated my W10 to version 1909 (the released version, not insider fast build). It seems that the transparency is still broken in this build. I tested as recently as yesterday on my insider fast build (on a separate boot drive) and it was working there. It is a pretty old insider fast build, don't recall the exact number, I installed it a couple days after I opened this issue.

Is it possible the transparency bug was removed or otherwise did not make it into the stable release?

**Comment by robmikh** [comment] 2020-01-22 01:29
No worries, what I told you was technically inaccurate. The fix I was talking about was slated for the 2004 build, not 1909. Apologizes for the mix up.

**Comment by NickThissen** [comment] 2020-01-22 08:37
Thanks, at least I know I didn't mess up my code..!

**Comment by Zofware** [comment] 2020-06-21 07:29
Thanks @robmikh! I can confirm that the transparency issue is definitely fixed in Windows 10 build 19041. It's great to finally be able to capture Xaml renders to DXGI surfaces with transparency!

**Comment by varKeytrap** [comment] 2021-01-02 00:17
@NickThissen, Hi, have you found a more performant way of getting the Bitmap from the Texture2D ? I tried your function but the app uses 20% of my processor.

**Comment by Kybs0** [comment] 2022-01-05 13:21
@robmikh Hi, I have updated win version to win11. But it works still not well, is there anything I have ignored?

**Comment by robmikh** [comment] 2022-01-05 20:01
Sorry, but there were quite a few things being discussed here, so I don't know what exactly you're talking about. Could you open a new issue and be specific about what you're doing/seeing and what you're expecting?
