### ISSUE TITLE
Display Screen capture excluding a WPF window with "AllowTransparency=true"

### ISSUE THREAD

**Issue by deepakakkil001** [microsoft/Windows.UI.Composition-Win32-Samples#56] opened 2020-05-13 18:03 UTC
I am starting from the ScreenCapture WPF sample, and trying to implement a feature that will allow screen capture of the full display excluding the WPF window that i have. I am using the SetWindowDisplayAffinity(handle, WDA_EXCLUDEFROMCAPTURE) in the WPF window to skip the window from screen capture (since i want to skip the window completely, instead of having the black region). 

In a regular WPF Window, the approach works fine and I am able to capture the screen skipping the WPF window. However, when the WPF window has AllowTransparenacy enabled, the SetWindowDisplayAffinity returns 0 and the screencapture retains the WPF window. 

Is this a known issue? Is there a way to work around this, i.e. to skip a semi transparent WPF window that the application owns from the screen capture?

Thanks in advance,

**Comment by robmikh** [comment] 2020-05-13 18:42
Hmmm, I haven't heard reports of this yet. After you've set `AllowTransparenacy` on the window, could you call [`GetWindowDisplayAffinity`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowdisplayaffinity) and see if it returns what you would expect?

Additionally, could you share what builds of windows you're running?

**Comment by deepakakkil001** [comment] 2020-05-14 06:01
I am running Windows Build 19041. I set the AllowTransparency for the WPF window in XAML and the calling GetWindowDisplayAffinity() once the window is loaded returns a display affinity setting of 0 (WDA_NONE), as expected.

It seems when i next call SetWindowDisplayAffinity() , it fails with a win32 error code of 8 _[Not enough storage is available to process this command]_. The error disappears when i set AllowTransparency back to false. I can recreate the behaviour on my computer with a minimal WPF project that only calls the SetWindowDisplayAffinity on loaded event.

**Comment by robmikh** [comment] 2020-05-16 19:17
Thanks for the info! I'm able to reproduce the issue and we're investigating internally.

**Comment by deepakakkil001** [comment] 2020-07-29 09:18
Hello, Any updates on this one? Thanks

**Comment by robmikh** [comment] 2020-07-29 20:16
Sorry, we don't have updates at this time. We still have the bug open and have identified the problem area in the code, we just haven't gotten to it yet.

**Comment by robmikh** [comment] 2021-01-22 03:37
Sorry, I forgot to update this after our investigation. The issue is that WPF internally uses [`UpdateLayeredWindow`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-updatelayeredwindow) in this scenario, which conflicts with the ability to call `SetWindowDisplayAffinity`. For the time being, this is by design. However, we may revise this in the future. Closing this issue for now.

**Closed by robmikh** 2021-01-22 03:37 UTC

**Comment by VladiStep** [comment] 2024-01-23 10:31
> Sorry, I forgot to update this after our investigation. The issue is that WPF internally uses [`UpdateLayeredWindow`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-updatelayeredwindow) in this scenario, which conflicts with the ability to call `SetWindowDisplayAffinity`. For the time being, this is by design. However, we may revise this in the future. Closing this issue for now.

Can you add more details?
Why does it conflict? And most importantly, is there any hack for it?

**Comment by robmikh** [comment] 2024-01-23 22:45
Unfortunately I can't go into further detail, and I don't have a workaround at the moment. But it just to happens I'll be looking at this again soon, and I'll update you on any workarounds I find or if we fix this issue.

**Comment by adammarks** [comment] 2025-04-29 20:44
@robmikh This problem appears to be fixed in Win11 24H2.  Is that the first version that should have this fixed?

**Comment by robmikh** [comment] 2025-04-29 21:33
To be honest with you, I didn't realize it was fixed in 24H2! I'll need to do some digging and see what fixed it.

**Comment by LemonPrefect** [comment] 2025-12-22 13:29
Hello, I might found a workaround works fine for me according to this [passage](https://blog.lindexi.com/post/WPF-%E5%88%B6%E4%BD%9C%E6%94%AF%E6%8C%81%E7%82%B9%E5%87%BB%E7%A9%BF%E9%80%8F%E7%9A%84%E9%AB%98%E6%80%A7%E8%83%BD%E7%9A%84%E9%80%8F%E6%98%8E%E8%83%8C%E6%99%AF%E5%BC%82%E5%BD%A2%E7%AA%97%E5%8F%A3.html).

In which indicate that we can use a hook to keep the layered flag `WS_EX_LAYERED` for a window when `AllowTransparency` is unset rather than `True`. Use the code below as an example, we can get a window [has transparency + click-through enabled + can't be captured ]

```csharp
    protected override void OnSourceInitialized(EventArgs e) {
        base.OnSourceInitialized(e);

        var hwnd = new WindowInteropHelper(this).Handle;

        SetWindowDisplayAffinity(hwnd, WDA_EXCLUDEFROMCAPTURE);
        ((HwndSource)PresentationSource.FromVisual(this)).AddHook((IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam,
            ref bool handled) => {
            if (msg == WM_STYLECHANGING && wParam == (long)GWL_EXSTYLE) {
                var styleStruct = Marshal.PtrToStructure<STYLESTRUCT>(lParam);

                styleStruct.styleNew |= WS_EX_LAYERED;
                styleStruct.styleNew |= WS_EX_TRANSPARENT;

                Marshal.StructureToPtr(styleStruct, lParam, false);

                handled = true;
            }

            return IntPtr.Zero;
        });
    }
```

```xaml
<Window x:Class="WPFTest.AnswerWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        WindowStyle="None"
        ResizeMode="NoResize"
        Background="#8000FFFF">
    <WindowChrome.WindowChrome>
        <WindowChrome GlassFrameThickness="-1"
                      CaptionHeight="0"
                      CornerRadius="0" />
    </WindowChrome.WindowChrome>
</Window>
```
